### ISSUE TITLE
Optional cursor color for overtype mode

### ISSUE THREAD

**Issue by Srekel** [AdamMaras/vscode-overtype#4]
I (currently) use the block render mode for the cursor. This means that there's no distinction for when I'm in overtype mode. It'd be nice if it turned red, or something. :)

Suggest to add an overtype.cursorColor setting. 

I'm not sure if that's something that's exposed to VS code plugins. If not, it should be suggested. :)

**Comment by AdamMaras** [comment]
Unfortunately, changing the cursor color (or any other themed color, as far as I know) isn't supported by Code's API and such a change isn't on their roadmap.

I'm going to close this for now, but we can open it back up if that functionality ever surfaces.
